// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package post

import (
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID         int32
	Body       string
	UserID     int32
	AuthorName string
	CreatedAt  time.Time
}

type Post struct {
	ID         int32
	Body       string
	UserID     int32
	AuthorName string
	ImageID    uuid.NullUUID
	CreatedAt  time.Time
}

type PostComment struct {
	ID        int32
	PostID    int32
	CommentID int32
}

type PostLike struct {
	PostID int32
	UserID int32
}
