// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package post

import (
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID         uuid.UUID
	Body       string
	UserID     uuid.UUID
	AuthorName string
	CreatedAt  time.Time
}

type Post struct {
	ID         uuid.UUID
	Body       string
	UserID     uuid.UUID
	AuthorName string
	ImageID    uuid.NullUUID
	CreatedAt  time.Time
}

type PostComment struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	CommentID uuid.UUID
}

type PostLike struct {
	PostID uuid.UUID
	UserID uuid.UUID
}
