// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package post

import (
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID         uuid.UUID
	Body       string
	Author     uuid.UUID
	AuthorName string
	ImageID    uuid.NullUUID
	CreatedAt  time.Time
}
