// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package userImages

import (
	"time"

	"github.com/google/uuid"
)

type UserImage struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ImageID   uuid.UUID
	CreatedAt time.Time
}
