// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package userImages

import (
	"time"

	"github.com/google/uuid"
)

type UserImage struct {
	ID        int32
	UserID    int32
	ImageID   uuid.UUID
	CreatedAt time.Time
}
