// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package users

import ()

type User struct {
	ID        int32
	Username  string
	Email     string
	Password  string
	FirstName string
	LastName  string
}
