// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package users

import (
	"github.com/google/uuid"
)

type User struct {
	ID        int32
	Username  string
	Email     string
	FirstName string
	LastName  string
}

type UserProfileImage struct {
	UserID  int32
	ImageID uuid.UUID
}
